FROM nimlang/nim:1.6.2-ubuntu

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN  apt-get update && apt-get install -y \
  libclang-12-dev \
  libldap2-dev \
  && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
RUN nimble build -y --passL:"-lclang-12"

RUN ./futhest